default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: artemruby
  password: artem

development:
  <<: *default
  database: artemdb

test:
  <<: *default
  database: artemdb

production:
  <<: *default
  database: artemdb
